nbc-team-gumi/goodbite-main

src/main/java/com/sparta/goodbite/domain/menu/controller/MenuController.java
src/main/java/com/sparta/goodbite/domain/menu/dto/CreateMenuRequestDto.java
src/main/java/com/sparta/goodbite/domain/menu/dto/MenuResponseDto.java
src/main/java/com/sparta/goodbite/domain/menu/dto/UpdateMenuRequestDto.java
src/main/java/com/sparta/goodbite/domain/menu/entity/Menu.java
src/main/java/com/sparta/goodbite/domain/menu/repository/MenuRepository.java
src/main/java/com/sparta/goodbite/domain/menu/service/MenuService.java

제목 : [✨FEAT] Menu 도메인 기능 구현
feat(issue 번호): #8 #9 #10 #11 
`Menu` 도메인 CRUD 기능 추가
커스텀 예외 처리 추가
resolved: #8 #9 #10 #11

7 feat menu 도메인 기능 구현

---

http/auth.http
http/customer.http

제목 : [🩹FIX] HTTP Client 핫픽스
feat(issue 번호):  #78 #79 
- 회원가입-로그인 정보 일치하도록 수정(편의)
- auth.http 쿠키 세팅 수정
- 
resolved: #78, resolved: #79

💯 test: http 테스트 수정

---

src/main/java/com/sparta/goodbite/domain/menu/entity/Menu.java
src/main/java/com/sparta/goodbite/domain/menu/repository/MenuRepository.java
src/main/java/com/sparta/goodbite/domain/menu/service/MenuService.java
src/main/java/com/sparta/goodbite/domain/restaurant/controller/RestaurantController.java
src/main/java/com/sparta/goodbite/domain/restaurant/service/RestaurantService.java

제목 : [✨FEAT] / 식당의 모든 메뉴 조회 메서드 추가
feat(issue 번호):
- RestaurantController에서 엔드포인트 정의 GET "/restaurants/{restaurantId}/menus"
- MenuService에서 조회 메서드 구현

63 refactor restaurant 도메인 인증인가 추가

---

http/waiting.http
src/main/java/com/sparta/goodbite/auth/security/WebSecurityConfig.java
src/main/java/com/sparta/goodbite/domain/waiting/controller/WaitingController.java
src/main/java/com/sparta/goodbite/domain/waiting/dto/WaitingResponseDto.java
src/main/java/com/sparta/goodbite/domain/waiting/entity/Waiting.java
src/main/java/com/sparta/goodbite/domain/waiting/repository/WaitingRepository.java
src/main/java/com/sparta/goodbite/domain/waiting/service/WaitingService.java

제목 :  [♻️REFACTOR] 권한에 따른 기능 제한 추가
feat(issue 번호): #59
- 인증/인가 기능 추가 후 기능 테스트
- update, remove 기능은 만든 손님이나 해당 레스토랑의 오너만 가능
- create, get 등의 기능은 제한이 필요하지 않음

59 refactor 권한에 따른 기능 제한 추가

---

src/main/java/com/sparta/goodbite/auth/security/EmailUserDetailsService.java

[✨FEAT] Owner 가입 승인 여부 검증
feat(issue 번호): #95 #96 
Onwer가 회원가입 시 입력한 사업자번호가 승인되었는지 로그인 때 검증합니다.
승인되지 않았다면 로그인할 수 없습니다.
resolved: #95, resolved: #96

✨ feat: Owner 가입 승인 여부 검증

---

src/main/java/com/sparta/goodbite/auth/security/WebSecurityConfig.java
src/main/java/com/sparta/goodbite/domain/operatinghour/service/OperatingHourService.java
src/main/java/com/sparta/goodbite/domain/restaurant/controller/RestaurantController.java
src/main/java/com/sparta/goodbite/domain/restaurant/service/RestaurantService.java

제목 : [♻️REFACTOR] operatinghour 도메인 영업시간 조회 로직 이동
feat(issue 번호):
- 영업시간 조회 로직 RestaurantService에서 OperatingHourService로 이동

♻️ refactor: RestaurantService 에 있던 영업 시간 조회 부분 이동

---

src/main/java/com/sparta/goodbite/exception/auth/detail/UnauthorizedException.java

[✨FEAT] UnauthorizedException 클래스 추가
feat(issue 번호): #98
- 예외 처리에 UnauthorizedException 추가
resolved: #98, resolved: #99

✨ feat: UnauthorizedException 클래스 추가

---

src/main/java/com/sparta/goodbite/domain/restaurant/service/RestaurantService.java
src/main/java/com/sparta/goodbite/domain/waiting/service/WaitingService.java

제목 : [🩹FIX] dev 병합 후 버그 수정
feat(issue 번호): #102 
- dev 실행 오류 해결
- RestaurantService OperatingHourRepository 주입
- WaitingService restaurant.getOwnerId() 부분 restaurant.getOwner().getId()로 수정
resolved: #102

🩹 fix: dev에 2차 병합 후 실행 오류 해결

---

src/main/java/com/sparta/goodbite/domain/customer/repository/CustomerRepository.java
src/main/java/com/sparta/goodbite/domain/customer/service/CustomerService.java
src/main/java/com/sparta/goodbite/domain/owner/repository/OwnerRepository.java
src/main/java/com/sparta/goodbite/domain/owner/service/OwnerService.java
src/main/java/com/sparta/goodbite/domain/waiting/repository/WaitingRepository.java
src/main/java/com/sparta/goodbite/domain/waiting/service/WaitingService.java

제목 : [♻️REFACTOR] 서비스 검증 로직 분리
feat(issue 번호): #104 #105 
- Customer 도메인 서비스 검증 로직 레포지토리로 분리
- Owner 도메인 서비스 검증 로직 레포지토리로 분리
resolved: #104 #105

♻️ refactor: DB를 조회하는 서비스 레이어의 검증 로직을 레포지토리 레이어로 분리

---

src/main/java/com/sparta/goodbite/auth/security/CorsConfig.java
src/main/java/com/sparta/goodbite/auth/security/WebSecurityConfig.java

제목 : [✨FEAT] / CORS 설정 추가
feat(issue 번호): #113 #114 
CORS 규칙 적용하여 외부에서의 요청이 올바르게 처리되도록 설정 추가
resolved: #113 #114

✨ feat: CORS 설정 추가

---

src/main/java/com/sparta/goodbite/domain/customer/controller/CustomerController.java
src/main/java/com/sparta/goodbite/domain/customer/service/CustomerService.java
src/main/java/com/sparta/goodbite/domain/owner/controller/OwnerController.java
src/main/java/com/sparta/goodbite/domain/owner/service/OwnerService.java

제목 : [♻️REFACTOR] Customer/Owner 다운캐스팅 로직의 레이어 이동
feat(issue 번호): #120 #127
- Customer/Owner 다운캐스팅 로직의 레이어 이동
- UserCredential에서 Customer/Owner로의 다운캐스팅 로직을 서비스가 아닌 컨트롤러에서 해결하여 불필요한 명시적 save도 제거
resolved: #127, resolved: #120

120 refactor 유저 캐스팅 로직 레이어 이동

---

http/waiting.http
src/main/java/com/sparta/goodbite/domain/waiting/entity/Waiting.java
src/main/java/com/sparta/goodbite/domain/waiting/repository/WaitingRepository.java
src/main/java/com/sparta/goodbite/domain/waiting/service/WaitingService.java

제목 : [🩹FIX] waiting 전체적인 수정
feat(issue 번호): #116 
- waiting을 soft-delete 할 수 있도록 수정
- waiting을 식당에서 받는 상황과 삭제/취소 상황 발생 시, waiting의 status를 변경하도록 수정
- 삭제/취소 기능 실행 시, status가 수정되고 waiting의 deletedAt필드가 수정됨
resolved: #116

112 front waiting 상태 변경 코드 추가

---

src/main/java/com/sparta/goodbite/domain/restaurant/controller/RestaurantController.java
src/main/java/com/sparta/goodbite/domain/restaurant/dto/RestaurantIdResponseDto.java
src/main/java/com/sparta/goodbite/domain/restaurant/service/RestaurantService.java

[✨FEAT] 사업자 자신의 restaurantId를 얻을 수 있는 API
feat(issue 번호): #132 #133 
- getMyRestaurant 메서드 추가
resolved: #132 , resolved: #133

✨ feat: 사업자 자신의 restaurantId를 얻을 수 있는 API

---

src/main/java/com/sparta/goodbite/domain/operatinghour/controller/OperatingHourController.java
src/main/java/com/sparta/goodbite/domain/operatinghour/dto/OperatingHourResponseDto.java
src/main/java/com/sparta/goodbite/domain/operatinghour/service/OperatingHourService.java

제목 : [✨FEAT] OperatingHour 단일 조회 기능 추가
feat(issue 번호): #139 
- OperatingHour 단일 조회 기능 추가
- OperatingHourResponseDto id값 응답 추가
resolved: #139

✨ feat: OperatingHour 단일 조회 기능 추가

---

src/main/java/com/sparta/goodbite/domain/waiting/dto/WaitingResponseDto.java

제목 : [♻️REFACTOR] waiting response 필드 추가
feat(issue 번호): #144 
review 작성 시 restaurantId가 필요해 필드 추가
resolved: #144

144 refactor waiting response 필드 추가

---

http/waiting.http
src/main/java/com/sparta/goodbite/domain/restaurant/controller/RestaurantController.java
src/main/java/com/sparta/goodbite/domain/waiting/controller/WaitingController.java
src/main/java/com/sparta/goodbite/domain/waiting/dto/WaitingResponseDto.java
src/main/java/com/sparta/goodbite/domain/waiting/service/WaitingService.java

[✨FEAT] 웨이팅 API 응답에 손님 정보 추가
feat(issue 번호): #135 
웨이팅 API 응답에 손님 정보 추가
resolved: #135, resolved: #136

✨ feat: 웨이팅 API 응답에 손님 정보 추가

---

src/main/java/com/sparta/goodbite/domain/restaurant/controller/RestaurantController.java
src/main/java/com/sparta/goodbite/domain/review/repository/ReviewRepository.java
src/main/java/com/sparta/goodbite/domain/review/service/ReviewService.java

제목 : [♻️REFACTOR] 리뷰 도메인 기능 추가 및 리팩토링
feat(issue 번호): #146 
식당 ID로 리뷰들 조회하는 기능 추가
resolved: #146

146 refactor 리뷰 도메인 기능 추가 및 리팩토링

---

src/main/resources/application-test.yml

제목 : [🩹FIX] application-test.yml ddl-auto 수정
feat(issue 번호): #154 
- application-test.yml ddl-auto: create-drop -> update 수정
resolved: #154

🩹 fix: application-test.yml ddl-auto 수정

---

src/main/java/com/sparta/goodbite/domain/customer/controller/CustomerController.java
src/main/java/com/sparta/goodbite/domain/customer/service/CustomerService.java
src/main/java/com/sparta/goodbite/domain/owner/controller/OwnerController.java
src/main/java/com/sparta/goodbite/domain/owner/service/OwnerService.java

제목 : [🩹FIX] 고객 및 사장 수정 삭제시 캐스팅하는 레이어 변경이후 데이터베이스에 저장되지 않는 오류 해결
feat(issue 번호): 150
고객 및 사장 수정 삭제시 캐스팅하는 레이어 변경이후 데이터베이스에 저장되지 않는 오류 해결
resolved: #151, resolved: #152, resolved: #150

150 bug 고객 및 사장 수정 삭제시 캐스팅하는 레이어 변경이후 데이터베이스에 저장되지 않는 오류 해결

---

src/main/java/com/sparta/goodbite/auth/security/JwtAuthorizationFilter.java

[🩹FIX] 로그인/회원가입 인가 문제 수정
feat(issue 번호): #156 
로그인, 회원가입 API가 보안 필터를 타지 않도록 수정
resolved: #156 , resolved: #157

🩹 fix: 로그인/회원가입 인가 문제 수정

---

src/main/java/com/sparta/goodbite/auth/util/JwtConfig.java
src/main/java/com/sparta/goodbite/auth/util/JwtUtil.java

[✨FEAT] CORS 이슈
feat(issue 번호): #170
- 쿠키에 AWS 서버 도메인 설정
resolved: #170

🩹 fix: CORS 이슈

---

Dockerfile
src/main/java/com/sparta/goodbite/auth/security/WebSecurityConfig.java

[🩹FIX] CORS 필터를 JwtAuthorization 필터 뒤에 명시
feat(issue 번호): #173 
dev 서버가 뜨지 않는 에러 수정
resolved: #173

🩹 fix: CORS 필터를 JwtAuthorization 필터 뒤에 명시

---

src/main/java/com/sparta/goodbite/domain/review/controller/ReviewController.java
src/main/java/com/sparta/goodbite/domain/review/repository/ReviewRepository.java
src/main/java/com/sparta/goodbite/domain/review/service/ReviewService.java

제목 : [✨FEAT] 본인이 작성한 리뷰 목록 조회 기능 추가
feat(issue 번호): #179
본인이 작성한 리뷰의 목록을 조회할 수 있는 API 엔드포인트 및 서비스 로직 구현
resolved: #179

179 feat 본인이 작성한 리뷰 목록 조회 기능 추가

---

src/main/java/com/sparta/goodbite/domain/review/dto/ReviewResponseDto.java

제목 : [✨FEAT] 리뷰 조회시 응답 목록 추가
feat(issue 번호): #190 
- 리뷰 조회시 사용자 닉네임, 가게 이름, 작성일 추가
resolved: #190

✨ feat: 리뷰 조회시 응답 목록 추가

---

src/main/java/com/sparta/goodbite/domain/reservation/dto/ReservationResponseDto.java

제목 : [♻️REFACTOR] 예약 도메인 리팩토링
feat(issue 번호): #209
예약 응답 DTO 수정
resolved: #209

209 refactor 예약 도메인 리팩토링

---

.github/workflows/github-action.yml
src/main/java/com/sparta/goodbite/auth/security/EmailUserDetailsService.java
src/main/java/com/sparta/goodbite/auth/security/JwtAuthorizationFilter.java
src/main/java/com/sparta/goodbite/auth/security/WebSecurityConfig.java
src/main/java/com/sparta/goodbite/domain/restaurant/controller/RestaurantController.java

[♻️REFACTOR] 인증인가 리팩토링
feat(issue 번호): #141 
인증인가 리팩토링
resolved: #141, resolved: #185

141 refactor 인증인가 리팩토링

---

src/main/java/com/sparta/goodbite/auth/security/JwtAuthorizationFilter.java
src/main/java/com/sparta/goodbite/domain/reservation/controller/ReservationController.java
src/main/java/com/sparta/goodbite/domain/reservation/entity/Reservation.java
src/main/java/com/sparta/goodbite/domain/reservation/service/ReservationService.java

제목 : [✨FEAT] 예약 기능 리팩토링
feat(issue 번호): #217 
- Reservation 엔티티 함수 수정
- 가게 입장 인가 경로 추가, ReservationController 버그 수정
- 오너가 예약 취소 시 상태 변경
resolved: #217

217 feat 예약 기능 리팩토링

---

src/main/java/com/sparta/goodbite/domain/review/service/ReviewService.java
src/main/java/com/sparta/goodbite/domain/waiting/repository/WaitingRepository.java
src/main/java/com/sparta/goodbite/exception/review/ReviewErrorCode.java
src/main/java/com/sparta/goodbite/exception/review/detail/ReviewNotAuthorizationException.java

제목 : [✨FEAT] 리뷰 웨이팅 입장한 손님만 작성 가능 로직 추가
feat(issue 번호): #206 
리뷰 웨이팅 입장한 손님만 작성 가능 로직 추가
resolved: #206

206 feat 리뷰 웨이팅 입장한 손님만 작성 가능 로직 추가

---

src/main/java/com/sparta/goodbite/common/s3/service/S3Service.java
src/main/java/com/sparta/goodbite/domain/menu/controller/MenuController.java
src/main/java/com/sparta/goodbite/domain/menu/dto/CreateMenuRequestDto.java
src/main/java/com/sparta/goodbite/domain/menu/dto/UpdateMenuRequestDto.java
src/main/java/com/sparta/goodbite/domain/menu/entity/Menu.java
src/main/java/com/sparta/goodbite/domain/menu/service/MenuService.java
src/main/java/com/sparta/goodbite/domain/restaurant/controller/RestaurantController.java
src/main/java/com/sparta/goodbite/domain/restaurant/service/RestaurantService.java
src/main/java/com/sparta/goodbite/exception/menu/MenuErrorCode.java
src/main/java/com/sparta/goodbite/exception/menu/detail/MenuCreateFailedException.java
src/main/java/com/sparta/goodbite/exception/menu/detail/MenuUpdateFailedException.java

제목 : [✨FEAT] 이미지 관련 기능 수정
feat(issue 번호): #232 
- 레스토랑 수정 시 이미지 첨부 안해도 수정 가능하도록 변경
- 메뉴 등록, 수정 시 s3를 이용하여 이미지 첨부방식으로 수정
resolved: #232

232 feat 이미지 관련 기능 수정

---

src/main/java/com/sparta/goodbite/domain/menu/entity/Menu.java
src/main/java/com/sparta/goodbite/domain/menu/repository/MenuRepository.java
src/main/java/com/sparta/goodbite/domain/menu/service/MenuService.java
src/main/java/com/sparta/goodbite/domain/reservation/controller/ReservationController.java
src/main/java/com/sparta/goodbite/domain/reservation/entity/Reservation.java
src/main/java/com/sparta/goodbite/domain/reservation/repository/ReservationRepository.java
src/main/java/com/sparta/goodbite/domain/reservation/service/ReservationService.java
src/main/java/com/sparta/goodbite/domain/restaurant/controller/RestaurantController.java
src/main/java/com/sparta/goodbite/domain/restaurant/entity/Restaurant.java
src/main/java/com/sparta/goodbite/domain/restaurant/repository/RestaurantRepository.java
src/main/java/com/sparta/goodbite/domain/restaurant/service/RestaurantService.java
src/main/java/com/sparta/goodbite/domain/review/controller/ReviewController.java
src/main/java/com/sparta/goodbite/domain/review/entity/Review.java
src/main/java/com/sparta/goodbite/domain/review/service/ReviewService.java
src/main/java/com/sparta/goodbite/domain/waiting/entity/Waiting.java
src/main/java/com/sparta/goodbite/domain/waiting/repository/WaitingRepository.java
src/main/java/com/sparta/goodbite/domain/waiting/service/WaitingService.java
src/main/java/com/sparta/goodbite/exception/GlobalExceptionHandler.java

제목 : [♻️REFACTOR] 조회 페이지네이션
feat(issue 번호): #229 
- 리뷰, 식당, 예약, 메뉴 조회 반환 타입을 리스트에서 페이지로 변경
resolved: #233 #234 #235 #236

229 refactor 조회 페이지네이션

---

src/main/java/com/sparta/goodbite/domain/menu/dto/UpdateMenuRequestDto.java
src/main/java/com/sparta/goodbite/domain/menu/dto/validation/validator/AtLeastOneFieldValidator.java
src/main/java/com/sparta/goodbite/domain/menu/repository/MenuRepository.java
src/main/java/com/sparta/goodbite/domain/menu/service/MenuService.java
src/main/java/com/sparta/goodbite/domain/reservation/repository/ReservationRepository.java
src/main/java/com/sparta/goodbite/domain/reservation/service/ReservationService.java
src/main/java/com/sparta/goodbite/domain/waiting/repository/WaitingRepository.java
src/main/java/com/sparta/goodbite/domain/waiting/service/WaitingService.java

제목 : [🩹FIX] 페이징 메소드 이름 변경
feat(issue 번호): #255 
- 페이징 메소드 이름 변경
- UpdateMenuRequestDto에서 imageUrl 필드 삭제
resolved: #255

255 bug 페이징 메소드 이름 변경

---

http/reservation.http
http/waiting.http
src/main/java/com/sparta/goodbite/domain/waiting/dto/PostWaitingRequestDto.java
src/main/java/com/sparta/goodbite/exception/GlobalExceptionHandler.java

제목 :  [♻️REFACTOR] 웨이팅 입력 제한
feat(issue 번호): 243
웨이팅 등록제한을 최소1 ~ 최대 10명으로 제한했습니다.
resolved: #243

🩹 fix: 웨이팅 등록 시, 인원제한(10명)

---

src/main/java/com/sparta/goodbite/domain/restaurant/dto/RestaurantRequestDto.java

[✨FEAT] 안심번호 정규식 추가
feat(issue 번호): #262 
안심번호 정규식 추가
resolved: #262

✨ feat: 안심번호 정규식 추가

---

src/main/java/com/sparta/goodbite/domain/customer/service/CustomerService.java
src/main/java/com/sparta/goodbite/domain/waiting/repository/WaitingRepository.java

제목 : [♻️REFACTOR] 손님 삭제 시 연결된 웨이팅예약 삭제
feat(issue 번호): 253
손님 삭제 시 연결된 웨이팅예약 하드 삭제
resolved: #253

253 refactor 손님 삭제 시 연결된 웨이팅과 예약 하드 딜리트

---

build.gradle
src/main/java/com/sparta/goodbite/domain/restaurant/config/QuerydslConfig.java
src/main/java/com/sparta/goodbite/domain/restaurant/controller/RestaurantController.java
src/main/java/com/sparta/goodbite/domain/restaurant/dto/RestaurantResponseDto.java
src/main/java/com/sparta/goodbite/domain/restaurant/entity/Restaurant.java
src/main/java/com/sparta/goodbite/domain/restaurant/repository/RestaurantRepository.java
src/main/java/com/sparta/goodbite/domain/restaurant/repository/RestaurantRepositoryCustom.java
src/main/java/com/sparta/goodbite/domain/restaurant/repository/RestaurantRepositoryCustomImpl.java
src/main/java/com/sparta/goodbite/domain/restaurant/service/RestaurantService.java
src/main/java/com/sparta/goodbite/domain/review/controller/ReviewController.java
src/main/java/com/sparta/goodbite/domain/review/dto/CreateReviewRequestDto.java
src/main/java/com/sparta/goodbite/domain/review/dto/ReviewResponseDto.java
src/main/java/com/sparta/goodbite/domain/review/dto/UpdateReviewRequestDto.java
src/main/java/com/sparta/goodbite/domain/review/dto/validation/validator/RatingValidator.java
src/main/java/com/sparta/goodbite/domain/review/entity/ReservationReview.java
src/main/java/com/sparta/goodbite/domain/review/entity/Review.java
src/main/java/com/sparta/goodbite/domain/review/entity/WaitingReview.java
src/main/java/com/sparta/goodbite/domain/review/service/ReservationReviewServiceImpl.java
src/main/java/com/sparta/goodbite/domain/review/service/ReviewService.java
src/main/java/com/sparta/goodbite/domain/review/service/TotalReviewService.java
src/main/java/com/sparta/goodbite/domain/review/service/WaitingReviewServiceImpl.java

제목 : [✨FEAT] 필터 기반 식당 조회 메서드 추가
feat(issue 번호):
QueryDSL을 사용하여 필터 기반 식당 목록 페이지네이션 조회 구현 및 엔드포인트 추가
resolved: #259

259 feat 필터 기반 식당 조회 메서드 추가
